blog/urls.py
from django.urls import path
from .views import blog_index
from .views import blog_detail
from .views import blog_category

app_name = "blog"

urlpatterns = [
    path("", blog_index, name="all_posts"),
    path("<int:pk>/", blog_detail, name="blog_detail"),
    path("<category>/", blog_category, name="blog_category")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls'))
]

projects/urls.py
from django.urls import path
from projects import views
from blog.urls import urlpatterns

app_name = "projects"
blog_entry = urlpatterns[0]
urlpatterns = [
    path("", views.all_projects, name="all_projects"),
    path("<int:pk>", views.project_detail, name="project_detail"),
]

blog/models.py
import datetime
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

class Posts(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateField(auto_now_add=True)
    last_update = models.DateField(auto_now=True)
    category = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "posts"

class Comments(models.Model):
    author = models.CharField(max_length=60)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    # many to one relationship
    post = models.ForeignKey('Posts', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "comments"

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

blog/forms.py
from django import forms
from .models import Category


cat = [(1, "hello"), (2, "hello2")]

def categories():
    # Convert list to indexed tuple list
    all_categories = Category.objects.all()
    list_tuple = []
    for i in range(0, len(all_categories)):
        list_tuple.append((i, all_categories[i].name))
    return list_tuple

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    text = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

class PostsForm(forms.Form):
    title = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Add title"
        })
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Add text"
            }
        )
    )
    #category = forms.MultipleChoiceField(required=True, choices=categories)
    category=forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple)

blog/views.py
from django.shortcuts import render
from blog.models import Posts, Comments
from .forms import CommentForm, PostsForm
# Create your views here.
import datetime

def blog_index(request):

    form = PostsForm()
    if request.method == 'POST':
        form = PostsForm(request.POST)
        if form.is_valid():
            new_post = Posts(
                title=form.cleaned_data["title"],
                text=form.cleaned_data["text"],
                created=datetime.datetime.now(),
                last_update=datetime.datetime.now(),
            )

            new_post.save()
            new_post.category.set(form.cleaned_data["category"])
            new_post.save()

    all_posts = Posts.objects.all().order_by('-created')

    context = {'posts': all_posts,
               'form': form}

    return render(request, 'blog/blog_index.html', context)

def blog_detail(request, pk):
    post = Posts.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comments(
                author=form.cleaned_data["author"],
                text=form.cleaned_data["text"],
                post=post
            )
            comment.save()


    comments = Comments.objects.filter(post=post.pk)
    context = {
        'post': post,
        'comments': comments,
        "form": form,
    }
    return render(request, 'blog/blog_detail.html', context)

def blog_category(request, category):
    posts = Posts.objects.filter(category__name__contains=category).order_by(
        '-created'
    )

    context = {
        'category': category,
        'posts': posts
    }
    return render(request, "blog/blog_category.html", context)

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from projects.models import Project

def all_projects(request):
    # query the db to return all project objects
    projects = Project.objects.all()
    return render(request,"projects/all_projects.html", {'projects': projects})

def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/detail.html', {'project': project})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/blog/blog_category.html
{% extends 'portfolio/base.html' %}

{% block content %}

<div class="col-md-8 offset-md-2">

    <h1>{{ category | title}}</h1>
    <hr>

{% for post in posts %}
    <a href="{% url 'blog:blog_detail' post.pk %}">
        <h2>{{ post.title }}</h2>
    </a>
     <small>
            {{ post.created }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.category.all %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
     </small>
    <p>{{ post.text | slice:"100" }} ...</p>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div class="col-md-8 offset-md-2">
    <h2>{{ post.title }}</h2>
    <hr>
        <small>
            <p>{{ post.last_update }} |
                Categories:
                   {% for category in post.category.all %}
                         <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }} </a>
                    {% endfor %}
            </p>
        </small>
        <p>{{ post.text | linebreaks }}</p>

        <h3>Leave a comment: </h3>
        <form action="/blog/{{ post.pk }}/" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.author }}
            </div>
            <div class="form-group">
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        {% if comments %}
        <br>
        <h3>Comments:</h3>
        <p>
            {% for comment in comments %}
               On {{ comment.created }}&nbsp;
                <b>{{ comment.author }}</b> wrote:
         </p>
         <p>{{ comment.text }}</p>
        <hr>
            {% endfor %}

        {% endif %}
</div>
{% endblock %}

blog/templates/blog/blog_index.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="col-md-8 offset-md-2">
<h1>Blog Index</h1>
<hr>
    {% for post in posts %}
    <h2>
        <a href="{% url 'blog:blog_detail' post.pk%}">
            {{ post.title }}
        </a>
    </h2>
    <small>
         {{ post.created }} |&nbsp;
        Categories:&nbsp;
         {% for category in post.category.all %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.text | slice:":100" }} ... </p>
    {% endfor %}
   <h3>Add new Post:</h3>
    <form action="/blog/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.text }}
        </div>
          <div class="form-group">
            {{ form.category }}
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Home</a>
            </li>
              <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:all_posts' %}">Blog</a>
            </li>
          </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
     {% endblock %}
</div>
</body>
</html>

projects/templates/projects/all_projects.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Home</a>
            </li>
              <li class="nav-item active">
              <a class="nav-link" href="#">Blog</a>
            </li>
          </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
     {% endblock %}
</div>
</body>
</html>

projects/templates/projects/detail.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>

{% endblock %}